name: Deploy to Preview Channel

on:
  pull_request:
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Setup pnpm first
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.15.0'  # Match your package.json packageManager
      
      # Setup Node.js with pnpm caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'  # LTS version that supports React 19
          cache: 'pnpm'  # Enable pnpm caching
      
      # Install dependencies and build
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build project
        run: pnpm run build
      
      # Deploy to Firebase Preview
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GATSBYWEB }}'
          expires: 30d
          projectId: ${{ secrets.PROJECT_ID }}
          channelId: preview
